spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ecommerce-checkout
    password: ecommerce-checkout
    virtual-host: ecommerce-checkout
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: ECOMMERCE_CHECKOUT_OWNER
    password: ECOMMERCE_CHECKOUT_OWNER
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 15000
            readTimeout: 15000
            loggerLevel: FULL # NONE, BASIC, HEADERS, FULL

server:
  port: 8181

management:
  server:
    port: 9191

client:
  tax:
    url: http://localhost:8443/
  mid-client:
    url: http://localhost:8443/