version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    volumes:
      - C:/Users/DEV/.wiremock:/home/wiremock
    ports:
      - "8443:8080"
    expose:
      - 8443
    command: ["--verbose", "--root-dir", "/home/wiremock"]