CREATE USER ECOMMERCE_CHECKOUT_OWNER IDENTIFIED BY ECOMMERCE_CHECKOUT_OWNER;
GRANT ALL PRIVILEGES TO ECOMMERCE_CHECKOUT_OWNER IDENTIFIED BY ECOMMERCE_CHECKOUT_OWNER;
GRANT CREATE SESSION TO ECOMMERCE_CHECKOUT_OWNER;

CREATE TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT DATAFILE 'TS_ECOMMERCE_CHECKOUT_DAT.dat' SIZE 20M AUTOEXTEND ON;
ALTER DATABASE DEFAULT TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT;

CREATE SEQUENCE ECOMMERCE_CHECKOUT_OWNER.SALE_ORDER_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ECOMMERCE_CHECKOUT_OWNER.SALE_ORDER
(
    ID             NUMBER(38,0) NOT NULL,
    CHANNEL_CODE   VARCHAR2(3) NOT NULL,
    COMPANY_CODE   VARCHAR2(3) NOT NULL,
    STORE_CODE     VARCHAR2(3) NOT NULL,
    POS            NUMBER(10,0) NOT NULL,
    ORDER_NUMBER   VARCHAR2(30) NOT NULL,
    TOTAL_VALUE    NUMBER(38,2) NOT NULL,
    FREIGHT_VALUE  NUMBER(38,2) NOT NULL,
    INVOICE_KEY    VARCHAR2(44),
    INVOICE_NUMBER VARCHAR2(30),
    ISSUANCE_DATE  TIMESTAMP,
    INVOICE_BASE64 CLOB,
    STATUS         VARCHAR2(30) NOT NULL CHECK (ORIG_DOC_TYPE IN ('IN_PROCESSING', 'PROCESSED', 'ERROR')),
    ERROR_REASON   VARCHAR2(1000),
    CREATED_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT PK_SALE_ORDER PRIMARY KEY (ID)
) PARTITION BY RANGE (CREATED_DATE) INTERVAL (INTERVAL '1' MONTH) (
    PARTITION P_START VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00')
) TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT;

CREATE INDEX ECOMMERCE_CHECKOUT_OWNER.IX_SALE_ORDER_01 ON ECOMMERCE_CHECKOUT_OWNER.SALE_ORDER (ORDER_NUMBER) TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT;