-- ATENÇÃO: Conectar com postgres
-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- CREATE USER
CREATE USER ECOMMERCE_CHECKOUT_OWNER WITH PASSWORD 'ECOMMERCE_CHECKOUT_OWNER';
GRANT ALL PRIVILEGES ON DATABASE ecommerce_db TO ECOMMERCE_CHECKOUT_OWNER;

-- ATENÇÃO: Conectar com ECOMMERCE_CHECKOUT_OWNER
-- CREATE SEQUENCE
CREATE SEQUENCE SALE_ORDER_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NO CYCLE;

-- CREATE TABLE
CREATE TABLE SALE_ORDER
(
    ID             BIGINT                              NOT NULL,
    CHANNEL_CODE   VARCHAR(3)                          NOT NULL,
    COMPANY_CODE   VARCHAR(3)                          NOT NULL,
    STORE_CODE     VARCHAR(3)                          NOT NULL,
    POS            BIGINT                              NOT NULL,
    ORDER_NUMBER   VARCHAR(30)                         NOT NULL,
    TOTAL_VALUE    NUMERIC(38, 2)                      NOT NULL,
    FREIGHT_VALUE  NUMERIC(38, 2)                      NOT NULL,
    INVOICE_KEY    VARCHAR(44),
    INVOICE_NUMBER VARCHAR(30),
    ISSUANCE_DATE  TIMESTAMP,
    INVOICE_BASE64 TEXT,
    STATUS         VARCHAR(30)                         NOT NULL CHECK (STATUS IN ('IN_PROCESSING', 'PROCESSED', 'ERROR')),
    ERROR_REASON   VARCHAR(1000),
    CREATED_DATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SALE_ORDER PRIMARY KEY (ID)
);

-- CREATE INDEX
CREATE INDEX IX_SALE_ORDER_01 ON SALE_ORDER (ORDER_NUMBER);

-- ATENÇÃO: Conectar com postgres
-- DROP
DROP OWNED BY ECOMMERCE_CHECKOUT_OWNER CASCADE;
DROP USER ECOMMERCE_CHECKOUT_OWNER;
DROP DATABASE ecommerce_db;