CREATE USER ECOMMERCE_CHECKOUT_OWNER IDENTIFIED BY ECOMMERCE_CHECKOUT_OWNER;
GRANT ALL PRIVILEGES TO ECOMMERCE_CHECKOUT_OWNER IDENTIFIED BY ECOMMERCE_CHECKOUT_OWNER;
GRANT CREATE SESSION TO ECOMMERCE_CHECKOUT_OWNER;

CREATE TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT DATAFILE 'TS_ECOMMERCE_CHECKOUT_DAT.dat' SIZE 20M AUTOEXTEND ON;
ALTER DATABASE DEFAULT TABLESPACE TS_ECOMMERCE_CHECKOUT_DAT;