name: Spring Boot CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify -Dmaven.test.skip=true
      - name: Unit And Acceptance Tests
        run: mvn -U -B -V clean test -DargLine="-Xms512M -Xmx2G -Xss4M" --quiet
      - name: Sonar
        run: mvn -U -B clean verify sonar:sonar -Dsonar.organization="Anderson Lemos" -Dsonar.projectKey=andersonlemos83_api-ecommerce-checkout -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="cb486c028e8fec20011c9040437ba9b4c7617796" -DargLine="-Xms512M -Xmx2G -Xss4M" --quiet
      - name: Package
        run: mvn -B clean package -Dmaven.test.skip=true -DargLine="-Xms512M -Xmx2G -Xss4M"