name: Spring Boot CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Unit And Acceptance Tests
        run: mvn -U -B -V clean test -DargLine="-Xms512M -Xmx2G -Xss4M" --quiet
      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN-api-ecommerce-checkout }}
          SONAR_TOKEN2: ${{ secrets.api-ecommerce-checkout-SONAR_TOKEN }}
        run: mvn -X -U -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization="andersonlemos83" -Dsonar.projectKey=andersonlemos83_api-ecommerce-checkout -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -DargLine="-Xms512M -Xmx2G -Xss4M" --quiet
      - name: Package
        run: mvn -B clean package -Dmaven.test.skip=true -DargLine="-Xms512M -Xmx2G -Xss4M"